"""empty message

Revision ID: ff6eadecf75a
Revises: b3fdfcf48956
Create Date: 2024-04-19 16:39:35.152575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6eadecf75a'
down_revision = 'b3fdfcf48956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('seeking_description', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, nomaxvalue=True, cycle=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, nomaxvalue=True, cycle=True),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('nextval(\'"Venue_id_seq"\'::regclass)'),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('nextval(\'"Artist_id_seq"\'::regclass)'),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('afternoon')
        batch_op.drop_column('morning')
        batch_op.drop_column('website')

    op.drop_table('show')
    # ### end Alembic commands ###
